event_name: "#Zadania na dziś"
task_phrase: 'Zadania'
history_dir: 'history'
max_tasks_per_day: 16
event_time:
  start: "8:00"
  end: "9:00"
$START_DATE: "2024-02-05"
event_horizon: "2024-07-17"

tasks:
  - name: $START_DATE
    category: "XXX"
    start_date: $START_DATE
    intervals:
      - range: [1, 1]
        repetitions: 1
      - range: [2, 4]
        repetitions: 1
      - range: [9, 16]
        repetitions: 1
      - range: [30, 35]
        repetitions: 1
    avoid_days:
      weekdays: [6, 5]
      dates: []

  - name: "Siłownia borek"
    category: "exercise"
    start_date:  $START_DATE
    intervals:
      - range: [ 1, 1 ]
        repetitions: 1
      - range: [3, 3]
        repetitions: 7
    avoid_days:
      weekdays: [6]

  - name: "Siłownia dom"
    category: "exercise"
    start_date:  $START_DATE
    intervals:
      - range: [ 1, 1 ]
        repetitions: 1
      - range: [ 3, 3 ]
        repetitions: 7
    avoid_days:
      weekdays: [ 6]
  - name: "Zone 2 - 45 min"
    category: "exercise"
    start_date:  $START_DATE
    intervals:
      - range: [ 1, 1 ]
        repetitions: 1
      - range: [ 4, 4 ]
        repetitions: 14
    avoid_days:
      weekdays: [ 6]