event_name: "#Zadania"
task_phrase: 'Zadania'
history_dir: 'history'
max_tasks_per_day: 12
event_time:
  start: "8:00"
  end: "9:00"
$START_DATE: "2024-08-19"

tasks:
  - name: Linux
    start_date: $START_DATE
    intervals:
      - range: [1, 1]
        repetitions: 1
      - range: [2, 4]
        repetitions: 1
      - range: [9, 16]
        repetitions: 1
      - range: [30, 35]
        repetitions: 1
    avoid_days:
      weekdays: [6]
      dates: []
  - name: Python
    start_date: $START_DATE
    intervals:
      - range: [1, 1]
        repetitions: 1
      - range: [2, 4]
        repetitions: 1
      - range: [9, 16]
        repetitions: 1
      - range: [30, 35]
        repetitions: 1
    avoid_days:
      weekdays: [6]
      dates: []