event_name: "#Zadania na dziś"
task_phrase: 'Zadania'
history_dir: 'history'
max_tasks_per_day: 9
event_time:
  start: "8:00"
  end: "9:00"

event_horizon: "2023-12-06"

tasks:
  - name: "#praca endpointy flask"
    category: "1"
    start_date: "2023-10-22"
    intervals:
      - range: [ 1, 1 ]
        repetitions: 3
      - range: [ 2, 4 ]
        repetitions: 1
      - range: [ 9, 16 ]
        repetitions: 1
      - range: [ 30, 35 ]
        repetitions: 1
    avoid_days:
      weekdays: [ 5, 6 ]
      dates: [ "2023-11-23", "2023-11-24", "2023-11-27" ]

  - name: "#praca doucz się spójrz na video z Mikołajem - jforg do paczek opublikowanych z oprogramowaniem, buildy pczki i artyteczkty"
    category: "2"
    start_date: "2023-10-22"
    intervals:
      - range: [1, 1]
        repetitions: 3
      - range: [2, 4]
        repetitions: 1
      - range: [9, 16]
        repetitions: 1
      - range: [30, 35]
        repetitions: 1
    avoid_days:
      weekdays: [5, 6]
      dates: ["2023-11-23", "2023-11-24", "2023-11-27"]

  - name: "ci/dc doucz się zrób podstawowy projekt z chat gpt"
    category: "3"
    start_date: "2023-10-22"
    intervals:
      - range: [1, 1]
        repetitions: 3
      - range: [2, 4]
        repetitions: 1
      - range: [9, 16]
        repetitions: 1
      - range: [30, 35]
        repetitions: 1
    avoid_days:
      weekdays: [5, 6]
      dates: ["2023-11-23", "2023-11-24", "2023-11-27"]


  - name: "#praca o co chodzi z proxy - doucz się"
    category: "4"
    start_date: "2023-10-22"
    intervals:
      - range: [1, 1]
        repetitions: 3
      - range: [2, 4]
        repetitions: 1
      - range: [9, 16]
        repetitions: 1
      - range: [30, 35]
        repetitions: 1
    avoid_days:
      weekdays: [5, 6]
      dates: ["2023-11-23", "2023-11-24", "2023-11-27"]
