event_name: "#Zadania na dziś"
task_phrase: "Zadania"
history_dir: 'history'
max_tasks_per_day: 21
event_time:
  start: "8:00"
  end: "9:00"

event_horizon: "2023-12-06"

tasks:
  - name: "Biceps Długa, Triceps Długa, Górne Pośladki, Pompki Podwyższenie"
    category: "exercise"
    start_date: "2023-10-16"
    intervals:
      - range: [7, 7]
        repetitions: 7
    avoid_days:
      weekdays: [1,2,3,4,5,6]

  - name: "Barki, Całe Pośladki"
    category: "exercise"
    start_date: "2023-10-16"
    intervals:
      - range: [7, 7]
        repetitions: 7
    avoid_days:
      weekdays: [0,2,3,4,5,6]

  - name: "45min Z2 + Podciąganie"
    category: "exercise"
    start_date: "2023-10-16"
    intervals:
      - range: [7, 7]
        repetitions: 7
    avoid_days:
      weekdays: [0,1,3,4,5,6]

  - name: "Pompki, Triceps Własny Ciężar, Jednonoga Przysiady"
    category: "exercise"
    start_date: "2023-10-16"
    intervals:
      - range: [7, 7]
        repetitions: 7
    avoid_days:
      weekdays: [0,1,2,4,5,6]

  - name: "Barki, Biceps Krótka"
    category: "exercise"
    start_date: "2023-10-16"
    intervals:
      - range: [7, 7]
        repetitions: 7
    avoid_days:
      weekdays: [0,1,2,3,5,6]
