event_name: "#Zadania"
task_phrase: 'Zadania'
history_dir: 'history'
max_tasks_per_day: 2
event_time:
  start: "8:00"
  end: "9:00"
start_date: "tomorrow"
intervals:
  - [1, 1]
  - [2, 4]
  - [9, 16]
  - [30, 35]
avoid_days:
  weekdays: [6]
  dates: []
tasks:
  - name: Linux
  - name: Python